services:
  api:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    depends_on:
      - database
    entrypoint: python lightsoff_api/__init__.py
    environment:
      - DATABASE_URI=postgresql://lightsoff:lightsoff@database:5432/lightsoff

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=lightsoff
      - POSTGRES_PASSWORD=lightsoff
      - POSTGRES_DB=lightsoff
    ports:
      - 5054:5432
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
