"""Change google_place_id column type

Revision ID: e6c76ef765af
Revises: 41bf75c9dfe7
Create Date: 2022-10-27 14:17:25.972732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e6c76ef765af"
down_revision = "41bf75c9dfe7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("place", sa.Column("created_at", sa.DateTime()))
    op.execute("UPDATE place SET created_at = NOW()")
    op.execute("ALTER TABLE place ALTER COLUMN created_at SET NOT NULL")

    op.drop_constraint("place_review_place_fkey", "place_review")
    op.execute("ALTER TABLE place ALTER COLUMN google_place_id TYPE TEXT")

    op.execute("ALTER TABLE place_review ALTER COLUMN google_place_id TYPE TEXT")
    op.create_foreign_key(
        "place_review_place_fkey",
        "place_review",
        "place",
        ["google_place_id"],
        ["google_place_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("place", "created_at")
    # ### end Alembic commands ###
